// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Dashing.Highcolumn = (function(_super) {
    __extends(Highcolumn, _super);

    function Highcolumn() {
      return Highcolumn.__super__.constructor.apply(this, arguments);
    }

    Highcolumn.prototype.createChart = function(series, categories, color) {
      var container;
      container = $(this.node).find('.highchart-container');
      if ($(container)[0]) {
        return this.chart = new Highcharts.Chart({
          chart: {
            renderTo: $(container)[0],
            type: "column",
            backgroundColor: color,
            marginTop: 2
          },
          title: {
            text: ' '
          },
          xAxis: {
            categories: categories
          },
          yAxis: {
            title: {
              enabled: false
            }
          },
          legend: {
            enabled: false
          },
          series: series,
          plotOptions: {
            column: {
              stacking: 'normal'
            }
          }
        });
      }
    };

    Highcolumn.prototype.onData = function(data) {
      return this.createChart(data.series, data.categories, data.color);
    };

    return Highcolumn;

  })(Dashing.Widget);

}).call(this);

//# sourceMappingURL=highcolumn.map
